### ISSUE TITLE
Diff command using two dots notation

### ISSUE THREAD

**Issue by r-ashraf** [minhlucvan/crgpt#10]
I feel like we should be using the ... notation instead of double dots .. 
If I have a mster/main branch, I create a new feature branch from it and do changes in my feature branch. Ideally I want to do PR review of all the changes I have done in my feature branch right. But since this tool does git diff with two dots, it also looks at changes done to master/main branch by others as well so my PR review has both - feature branch changes as well as master changes

**Comment by minhlucvan** [comment]
added to new replease: https://www.npmjs.com/package/crgpt/v/1.2.0
