### ISSUE TITLE
ignoreFiles wildcard match

### ISSUE THREAD

**Issue by rmahnovetsky** [minhlucvan/crgpt#7]
ignoreFiles current does an exact match. Can you also make this a wildcard match? like 

/var/log/** will match all files in /var/log and all files in all child directories, recursively.
/var/log/**/*.log will match all files whose names end in .log in /var/log and all files in all child directories, recursively.
/home/*/.bashrc will match all .bashrc files in all user's home directories.
/home/*/.ssh/**/*.key will match all files ending in .key in all user's .ssh directories in all user's home directories.

I have a load of generated files that change over time and I don't want them to be PRed.

**Comment by minhlucvan** [comment]
added to new replease: https://www.npmjs.com/package/crgpt/v/1.2.0
